services:
  - type: web
    name: pruebatecnica-backend
    env: node
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URL
        sync: false # Lo configurarás manualmente
      - key: JWT_SECRET
        sync: false # Lo configurarás manualmente
